name: location_context_example
description: Example for using the location_context package
publish_to: none

version: 3.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  location_context:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

false_secrets:
  - lib/main.dart

flutter:
  uses-material-design: true
