name: location_context
description: Helper widgets to share location data using InheritedWidgets
version: 3.0.0
homepage: https://flutter.institute/
repository: https://github.com/flutter-institute/location_context
issue_tracker: https://github.com/flutter-institute/location_context/issues

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  location: ^5.0.3
  quiver: ^3.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  location_platform_interface: ^3.1.1

false_secrets:
  - example/lib/.env.dart.example

flutter:
  uses-material-design: true
