name: location_context
description: Helper widgets to share location data using InheritedWidgets
version: 1.1.0
author: Brian Armstrong <brian@flutter.institute>
homepage: https://flutter.institute/

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  location: ^3.0.2
  quiver: "^2.1.3"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
