name: location_context
description: Helper widgets to share location data using InheritedWidgets
version: 2.0.0
homepage: https://flutter.institute/
repository: https://github.com/flutter-institute/location_context
issue_tracker: https://github.com/flutter-institute/location_context/issues

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  location: ^4.4.0
  quiver: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
